// Package main provides a code generator for creating consumer-side template accessors.
// It scans a directory for HTML templates and generates a wrapper with typed helper methods.
//
// Usage:
//
//	go run generate_methods.go [flags]
//
// Flags:
//
//	-templates string
//	  	Directory containing template files (default "templates")
//	-out string
//	  	Output file for generated code (default "./templator_accessors_gen.go")
//	-package string
//	  	Package name for generated code (default "main")
//	-templator-import string
//	  	Import path for templator (default "github.com/alesr/templator")
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/alesr/templator"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

const methodsTemplate = `{{ define "header" }}// Code generated by go generate; DO NOT EDIT.
package {{.PackageName}}

import "{{ .TemplatorImport }}"

// TemplateAccessors provides typed helper accessors over templator Registry.
type TemplateAccessors[T any] struct {
	registry *templator.Registry[T]
}

// NewTemplateAccessors creates a TemplateAccessors wrapper for a templator Registry.
func NewTemplateAccessors[T any](registry *templator.Registry[T]) *TemplateAccessors[T] {
	return &TemplateAccessors[T]{registry: registry}
}

{{ end }}

{{ define "method" }}
// {{ .MethodName }} returns a handler for the {{ .TemplateName }} template.
func (r *TemplateAccessors[T]) {{.MethodName}}() (*templator.Handler[T], error) {
	return r.registry.Get("{{ .TemplateName }}")
}
{{ end }}`

type (
	TemplateData struct {
		MethodName   string
		TemplateName string
	}
	headerData struct {
		PackageName     string
		TemplatorImport string
	}
	config struct {
		templateDir     string
		outputFile      string
		packageName     string
		templatorImport string
	}
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := parseFlags()
	if err != nil {
		return err
	}

	tmpl, err := loadTemplateGenerator()
	if err != nil {
		return err
	}
	return generateMethods(cfg, tmpl)
}

func parseFlags() (config, error) {
	flagSet := flag.NewFlagSet("generate", flag.ExitOnError)
	templateDir := flagSet.String(
		"templates",
		templator.DefaultTemplateDir,
		"directory containing the template files",
	)
	outputFile := flagSet.String(
		"out",
		"./templator_accessors_gen.go",
		"output file for generated accessors",
	)
	packageName := flagSet.String(
		"package",
		"main",
		"package name for generated code",
	)
	templatorImport := flagSet.String(
		"templator-import",
		"github.com/alesr/templator",
		"templator import path",
	)

	flagSet.Parse(os.Args[1:])

	cfg := config{
		templateDir:     *templateDir,
		outputFile:      *outputFile,
		packageName:     *packageName,
		templatorImport: *templatorImport,
	}

	if err := cfg.validate(); err != nil {
		return config{}, err
	}
	return cfg, nil
}

func (c config) validate() error {
	if c.packageName == "" {
		return errors.New("requires non-empty -package")
	}
	if c.templatorImport == "" {
		return errors.New("requires non-empty -templator-import")
	}
	return nil
}

func loadTemplateGenerator() (*template.Template, error) {
	tmpl, err := template.New("generator").Parse(methodsTemplate)
	if err != nil {
		return nil, fmt.Errorf("could not parse code generator template: %w", err)
	}
	return tmpl, nil
}

func generateMethods(cfg config, tmpl *template.Template) error {
	var buf bytes.Buffer
	if err := writeHeader(&buf, cfg, tmpl); err != nil {
		return fmt.Errorf("could not write header: %w", err)
	}

	if err := processTemplates(cfg, &buf, tmpl); err != nil {
		return fmt.Errorf("could not process templates: %w", err)
	}

	if err := writeOutput(cfg.outputFile, &buf); err != nil {
		return fmt.Errorf("could not write output: %w", err)
	}
	fmt.Println("Methods generated and formatted successfully.")

	return nil
}

func writeHeader(buf *bytes.Buffer, cfg config, tmpl *template.Template) error {
	return tmpl.ExecuteTemplate(buf, "header", headerData{
		PackageName:     cfg.packageName,
		TemplatorImport: cfg.templatorImport,
	})
}

func processTemplates(cfg config, buf *bytes.Buffer, tmpl *template.Template) error {
	return filepath.Walk(cfg.templateDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return fmt.Errorf("could not walk directory: %w", err)
		}

		if info.IsDir() {
			return nil
		}

		if filepath.Ext(path) != string(templator.ExtensionHTML) {
			return nil
		}
		return generateTemplateMethod(path, cfg, buf, tmpl, cases.Title(language.English))
	})
}

func generateTemplateMethod(path string, cfg config, buf *bytes.Buffer, tmpl *template.Template, caser cases.Caser) error {
	relPath, err := filepath.Rel(cfg.templateDir, path)
	if err != nil {
		return fmt.Errorf("could not get relative path: %w", err)
	}

	data, err := buildTemplateData(relPath, caser)
	if err != nil {
		return fmt.Errorf("could not build template data: %w", err)
	}

	if err := tmpl.ExecuteTemplate(buf, "method", data); err != nil {
		return fmt.Errorf("could not execute template: %w", err)
	}
	buf.WriteString("\n")

	return nil
}

func buildTemplateData(relPath string, caser cases.Caser) (TemplateData, error) {
	basePath := strings.TrimSuffix(relPath, string(templator.ExtensionHTML))
	parts := strings.Split(basePath, string(filepath.Separator))
	for i, part := range parts {
		parts[i] = caser.String(part)
	}

	return TemplateData{
		MethodName:   "Get" + strings.Join(parts, ""),
		TemplateName: filepath.ToSlash(basePath),
	}, nil
}

func writeOutput(outputFile string, buf *bytes.Buffer) error {
	formattedSource, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("could not format generated code: %w", err)
	}
	return os.WriteFile(outputFile, formattedSource, 0o644)
}
